name: deploy-reactApp

on:
  push:
      branches:
        - master
      paths:
        - 'mf-react-product/**'

defaults:
  run: 
    working-directory: mf-react-product

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build:webpack
        env: 
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - uses: jsanz1209/aws-cli@1.0.0
        with: 
          args: s3 sync mf-react-product/dist s3://${{ secrets.AWS_S3_BUCKET_NAME_REACT }}/app2
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - uses: jsanz1209/aws-cli@1.0.0
        with: 
          args: cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/app2/team-product-mf-product.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}